# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:			/:categories/:title:output_ext

# Setup
title:               "Gammametric"
tagline:             'Freight dispatcher'
description:         'Gammametric is a freight market consulting and dispatching firm.'
url:                 'https://gammametric.com'
baseurl:             ''
plugins: [jekyll-seo-tag, jekyll-sitemap, jekyll-redirect-from]

# About/contact
author:
  name:              GammaMetric Solutions
  url:               http://gammametric.com
  email:             info@gammametric.com

# Social media
twitter_username:	gammametric

# Custom vars
version:             1.0.0
